# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b0476704c7126dbe5b9e891f65c5645edde0586bb40716217ec57248d417debfbe39c18a410a1426eaccee449c4f77c54cfa9b2450ae001a873699c43ee0871

test:
  secret_key_base: 6db943aade5d492657d07fcfa023b5ba9a9f627f6c358338c4ed684eaa4ca13753cce3e06199ee158af205d24613375a7ca9aad0f4fa2e381ba2b063b27c9b42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
